services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ENV=production  # Add any necessary environment variables
    volumes:
      - .:/app          # Optional: Mount the current directory to the container for development
    restart: always      # Optional: Ensure the container restarts if it fails
